r"""Build the four manuals (operation manual and code guide, English and Chinese).

    python docs/tools/build_manuals.py            # extract snippets + compile PDFs
    python docs/tools/build_manuals.py --check    # only verify every snippet still exists

How the code guide stays in sync with the code: the .tex files never paste
code. They write \snippet{app/causal/metrics.py:true_qini}. This script finds
that function or class with Python's ast module, reads its current first and
last line, and writes generated/snippets.tex, which tells LaTeX to print
exactly those lines from the real source file. If a referenced name no
longer exists, the build stops with an error.
"""

from __future__ import annotations

import argparse
import ast
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
MANUAL = ROOT / "docs" / "manual"
GENERATED = MANUAL / "generated"
SNIPPET = re.compile(r"\\snippet\{([^}:]+):([^}]+)\}")
DOCS = ["operation_manual_en", "operation_manual_zh", "code_guide_en", "code_guide_zh"]
BS = "\\"  # one backslash, to keep the LaTeX strings below readable


def find_span(path: Path, qualname: str) -> tuple[int, int]:
    """First and last line of a top-level function/class, Class.method, or a module constant."""
    tree = ast.parse(path.read_text(encoding="utf-8"))
    nodes, target = tree.body, None
    for part in qualname.split("."):
        defs = [n for n in nodes if isinstance(n, (ast.FunctionDef, ast.ClassDef, ast.AsyncFunctionDef)) and n.name == part]
        consts = [n for n in nodes if isinstance(n, ast.Assign) and any(getattr(t, "id", None) == part for t in n.targets)]
        target = (defs + consts or [None])[0]
        if target is None:
            raise KeyError(f"{qualname} not found in {path.relative_to(ROOT).as_posix()}")
        nodes = getattr(target, "body", [])
    start = min([target.lineno] + [d.lineno for d in getattr(target, "decorator_list", [])])
    return start, target.end_lineno


def snippet_definition(rel: str, qualname: str, first: int, last: int) -> str:
    title = f"{BS}texttt{{{rel.replace('_', BS + '_')}}}, lines {first}--{last}"
    listing = (
        f"{BS}lstinputlisting[firstline={first},lastline={last},firstnumber={first},"
        f"title={{{title}}}]{{../../{rel}}}"
    )
    return f"{BS}expandafter{BS}def{BS}csname snip@{rel}:{qualname}{BS}endcsname{{{listing}}}\n"


def extract() -> int:
    """Write generated/snippets.tex with one definition per snippet used in the manuals."""
    GENERATED.mkdir(parents=True, exist_ok=True)
    refs = set()
    for doc in DOCS:
        tex = MANUAL / f"{doc}.tex"
        if tex.exists():
            refs |= set(SNIPPET.findall(tex.read_text(encoding="utf-8")))
    errors, lines = [], ["% Generated by docs/tools/build_manuals.py. Do not edit.\n"]
    for rel, qualname in sorted(refs):
        try:
            first, last = find_span(ROOT / rel, qualname)
        except (KeyError, FileNotFoundError) as exc:
            errors.append(str(exc))
            continue
        lines.append(snippet_definition(rel, qualname, first, last))
    if errors:
        print("Missing code referenced by the manuals:\n  " + "\n  ".join(errors))
        sys.exit(1)
    (GENERATED / "snippets.tex").write_text("".join(lines), encoding="utf-8")
    print(f"{len(refs)} snippets extracted")
    return len(refs)


MODELS = {"churn_risk": "Risk", "kmeans": "Kmeans", "constant_ate": "Const", "t_learner": "Tl",
          "x_learner": "Xl", "causal_forest": "Cf", "ipw": "Ipw", "oracle": "Oracle", "random": "Random"}


def _f(x, digits: int = 2, sign: bool = False) -> str:
    """Number for LaTeX math-free text: thousands separators, real minus sign."""
    if x is None:
        return "--"
    s = f"{x:+,.{digits}f}" if sign else f"{x:,.{digits}f}"
    return s.replace("-", "$-$").replace(",", "{,}")


def results_macros() -> int:
    r"""Write generated/results.tex: one \R... macro per number quoted in the manuals,
    read from artifacts/reports/benchmark_summary.json (the file kept in git)."""
    import json

    summary = json.loads((ROOT / "artifacts" / "reports" / "benchmark_summary.json").read_text(encoding="utf-8"))
    e, b = summary["experiment"], summary["benchmark"]
    head, obs, c = b["headline"], b["observed_readout_draw0"]["abs_gain_customers"], summary["campaign"]
    lin, dim, op = e["ate_lin_pp"], e["ate_diff_in_means_pp"], e["observational_pp"]
    sig = lin["ci_low"] > 0 or lin["ci_high"] < 0
    rel, med = head["relative_gain_ratio_of_totals"], head["median_relative_gain"]
    wins = round(head["share_of_draws_uplift_wins"] * b["n_draws"])
    m = {
        "RnSubs": _f(summary["n_subscribers"], 0), "Rdraws": str(b["n_draws"]),
        "RnTreat": _f(e["n_treat"], 0), "RnControl": _f(e["n_control"], 0),
        "RsrmP": _f(e["srm_p"], 3), "RmaxSMD": _f(e["max_abs_smd"], 3),
        "RlinEst": _f(lin["estimate"]), "RlinLo": _f(lin["ci_low"]), "RlinHi": _f(lin["ci_high"]),
        "RlinSig": "significant at 5\\%" if sig else "not significant at 5\\%",
        "RlinSigZh": "5\\% 水平下显著" if sig else "5\\% 水平下不显著",
        "RdimEst": _f(dim["estimate"]), "RdimLo": _f(dim["ci_low"]), "RdimHi": _f(dim["ci_high"]),
        "RtrueATE": _f(e["true_ate_pp"]), "RchurnC": _f(e["churn_control_pct"]), "RchurnT": _f(e["churn_treat_pct"]),
        "RobsNaive": _f(op["naive"]), "RobsIpw": _f(op["ipw"]), "RobsAipw": _f(op["aipw"], sign=True),
        "RobsAipwSE": _f(op["aipw_se"]), "RsmdBefore": _f(e["max_abs_smd_before_weighting"]),
        "RsmdAfter": _f(e["max_abs_smd_after_weighting"], 3),
        "RgainRel": _f(100 * rel["estimate"], 1), "RgainRelLo": _f(100 * rel["ci_low"], 1),
        "RgainRelHi": _f(100 * rel["ci_high"], 1),
        "RgainMed": _f(100 * med["median"], 1), "RgainMedLo": _f(100 * med["ci_low"], 1),
        "RgainMedHi": _f(100 * med["ci_high"], 1),
        "RgainAbs": _f(head["abs_gain_customers"]["mean"], 1), "RgainAbsLo": _f(head["abs_gain_customers"]["ci_low"], 1),
        "RgainAbsHi": _f(head["abs_gain_customers"]["ci_high"], 1), "Rwins": str(wins),
        "RobsGain": _f(obs["median"], 0), "RobsGainLo": _f(obs["ci_low"], 0), "RobsGainHi": _f(obs["ci_high"], 0, sign=True),
        "RdrChoices": ", ".join(f"{k.replace('_', ' ')} {v}" for k, v in b["dr_choice_counts"].items()),
        "RnOffers": _f(c["n_offers"], 0), "RpredSaved": _f(c["predicted_saved"], 1), "RtrueSaved": _f(c["true_saved"], 1),
        "RpredNet": _f(c["predicted_net_value"], 0, sign=True), "RtrueNet": _f(c["true_net_value"], 0, sign=True),
        "RoracleNet": _f(c["oracle_net_value"], 0), "RtauSD": _f(c["true_cate_sd_pp"]),
    }
    ex = c.get("customer_42")
    if ex:
        m.update({"RexRisk": _f(100 * ex["churn_risk"], 1), "RexTau": _f(100 * ex["tau_hat"]),
                  "RexValue": _f(ex["value"]), "RexCost": _f(ex["offer_cost"]), "RexFee": _f(ex["monthly_fee"]),
                  "RexNet": _f(ex["net_value"], sign=True),
                  "RexDecision": "send an offer" if ex["tau_hat"] > 0 and ex["net_value"] > 0 else "do not contact",
                  "RexDecisionZh": "发优惠" if ex["tau_hat"] > 0 and ex["net_value"] > 0 else "不要联系"})
    for name, short in MODELS.items():
        row = b["table_mean"].get(name, {})
        m[f"Rpehe{short}"] = _f(row.get("pehe_pp"))
        m[f"Rqini{short}"] = _f(row.get("qini_true_normalized"))
        m[f"Rpol{short}"] = _f(row.get("policy_true"), 1)
        m[f"Rnet{short}"] = _f(row.get("netpolicy_true_net_value"), 0) if "netpolicy_true_net_value" in row else "--"
    lines = ["% Generated by docs/tools/build_manuals.py from artifacts/reports/benchmark_summary.json.\n"]
    lines += [f"\\newcommand{{\\{k}}}{{{v}}}\n" for k, v in m.items()]
    GENERATED.mkdir(parents=True, exist_ok=True)
    (GENERATED / "results.tex").write_text("".join(lines), encoding="utf-8")
    return len(m)


def compile_pdfs(only: list[str] | None = None) -> None:
    """Compile with xelatex into a temporary folder, then copy the PDF back.

    Build files go outside the project folder because cloud-sync clients
    (OneDrive, Dropbox) can corrupt .aux files while LaTeX is writing them.
    Two passes: the first writes the table of contents, the second prints it.
    """
    for doc in only or DOCS:
        if not (MANUAL / f"{doc}.tex").exists():
            continue
        with tempfile.TemporaryDirectory() as tmp:
            cmd = ["xelatex", "-interaction=nonstopmode", "-halt-on-error", f"-output-directory={tmp}", f"{doc}.tex"]
            for _ in range(2):
                result = subprocess.run(cmd, cwd=MANUAL, capture_output=True, text=True, encoding="utf-8", errors="replace")
                if result.returncode != 0:
                    print(result.stdout[-4000:])
                    sys.exit(f"LaTeX failed for {doc}")
            shutil.copy(Path(tmp) / f"{doc}.pdf", MANUAL / f"{doc}.pdf")
        print(f"built docs/manual/{doc}.pdf")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="only verify snippets")
    parser.add_argument("--only", nargs="*", help="build only these documents")
    args = parser.parse_args()
    extract()
    print(f"{results_macros()} result numbers read from benchmark_summary.json")
    if not args.check:
        compile_pdfs(args.only)


if __name__ == "__main__":
    main()
